using UnityEngine;
using Photon.Pun;
using ExitGames.Client.Photon;

public class DoorController : MonoBehaviourPunCallbacks
{
    public Animator doorAnimator;
    public Collider teleportTriggerZone;
    public string doorLockKey = "DoorLocked";

    void Start()
    {
        // On commence avec la porte verrouillÃ©e
        teleportTriggerZone.enabled = false;
    }

    void Update()
    {
        if (!PhotonNetwork.IsMasterClient) return; // seul le Master contrÃ´le l'Ã©tat global de la porte

        if (Input.GetKeyDown(KeyCode.P))
        {
            if (!IsDoorLocked())
            {
                OpenDoor();
            }
            else
            {
                Debug.Log("ðŸš« Porte verrouillÃ©e !");
            }
        }
    }

    void OpenDoor()
    {
        Debug.Log("ðŸšª Ouverture de la porte");
        doorAnimator.SetTrigger("Open");
        teleportTriggerZone.enabled = true;
    }

    public static bool IsDoorLocked()
    {
        if (PhotonNetwork.CurrentRoom.CustomProperties.TryGetValue("DoorLocked", out object locked))
        {
            return (bool)locked;
        }
        return false;
    }

    public static void SetDoorLock(bool locked)
    {
        Hashtable props = new Hashtable();
        props["DoorLocked"] = locked;
        PhotonNetwork.CurrentRoom.SetCustomProperties(props);
    }
}